# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_intentos_id_problema'),
        ('profesores', '0003_grupoxprofesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionesxGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Estudiantes')),
                ('ID_Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.Grupo')),
            ],
        ),
    ]
