# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0004_asignacionesxgrupo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupo',
            new_name='Grupos',
        ),
        migrations.RemoveField(
            model_name='asignacionesxgrupo',
            name='Estudiante',
        ),
        migrations.RemoveField(
            model_name='asignacionesxgrupo',
            name='ID_Grupo',
        ),
        migrations.RemoveField(
            model_name='grupoxprofesor',
            name='ID_Grupo',
        ),
        migrations.RemoveField(
            model_name='grupoxprofesor',
            name='ID_Prof',
        ),
        migrations.DeleteModel(
            name='AsignacionesxGrupo',
        ),
        migrations.DeleteModel(
            name='GrupoxProfesor',
        ),
    ]
