# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0006_profesor_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='Descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problemas',
            name='Descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='ApellidoMaterno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='ApellidoPaterno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Matricula',
            field=models.TextField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Nombres',
            field=models.TextField(),
        ),
    ]
