# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0007_auto_20171115_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('Matricula', models.TextField(max_length=8, primary_key=True, serialize=False)),
                ('ApellidoPaterno', models.TextField()),
                ('ApellidoMaterno', models.TextField()),
                ('Nombres', models.TextField()),
                ('Grupo', models.ManyToManyField(to='profesores.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tiempo', models.DurationField(null=True)),
                ('CantInstrucciones', models.PositiveIntegerField()),
                ('Matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profesores.Estudiantes')),
            ],
        ),
        migrations.AddField(
            model_name='problemas',
            name='IDIntentos',
            field=models.ManyToManyField(to='profesores.Intentos'),
        ),
    ]
