# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0008_auto_20171126_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='id',
        ),
        migrations.AlterField(
            model_name='grupos',
            name='Descripcion',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
