# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-02 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0013_auto_20180301_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='num_list',
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='Cuatro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='Dos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='Tres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='Uno',
            field=models.BooleanField(default=False),
        ),
    ]
