# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0006_profesor_grupo'),
        ('alumnos', '0002_intentos_id_problema'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='Grupo',
            field=models.ManyToManyField(to='profesores.Grupos'),
        ),
    ]
