# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20171114_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='ApellidoMaterno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='ApellidoPaterno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='Matricula',
            field=models.TextField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='Nombres',
            field=models.TextField(),
        ),
    ]
