# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_auto_20171115_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentos',
            name='Tiempo',
            field=models.DurationField(null=True),
        ),
    ]
