# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-17 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_auto_20180416_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimieto',
            name='velocidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carro',
            name='velocidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
