# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-17 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_auto_20180417_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='Nombre',
            field=models.TextField(default=''),
        ),
    ]
